-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 18:51:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hicorp_segment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hicorp_segment` ;

-- -----------------------------------------------------
-- Schema hicorp_segment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hicorp_segment` DEFAULT CHARACTER SET utf8 ;
USE `hicorp_segment` ;

-- -----------------------------------------------------
-- Table `hicorp_segment`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`user` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`user` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `user_name` VARCHAR(16) NOT NULL COMMENT 'User login account.',
                                                       `password` VARCHAR(255) NOT NULL COMMENT 'User login password',
                                                       `create_gmt` DATETIME NOT NULL COMMENT 'Record create time  (Use Greenwich Mean Time).',
                                                       `modified_gmt` DATETIME NOT NULL COMMENT 'Record modified time  (Use Greenwich Mean Time).',
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = 'This table just used to authenticate user login, only has account info, don`t has other user info.';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`role` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`role` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(16) NOT NULL,
                                                       `introduction` VARCHAR(255) NOT NULL,
                                                       `create_gmt` DATETIME NOT NULL,
                                                       `create_user` VARCHAR(45) NOT NULL,
                                                       `modified_user` VARCHAR(45) NULL,
                                                       `modified_gmt` DATETIME NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = 'This table stores role information.';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`user_role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`user_role_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`user_role_relation` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `user_id` BIGINT UNSIGNED NOT NULL,
                                                                     `role_id` BIGINT UNSIGNED NOT NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_user_role_relation_user_idx` (`user_id` ASC) VISIBLE,
                                                                     INDEX `fk_user_role_relation_role_idx` (`role_id` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_user_role_relation_user1`
                                                                         FOREIGN KEY (`user_id`)
                                                                             REFERENCES `hicorp_segment`.`user` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_user_role_relation_role1`
                                                                         FOREIGN KEY (`role_id`)
                                                                             REFERENCES `hicorp_segment`.`role` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`menu` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`menu` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `parent_id` BIGINT UNSIGNED NULL,
                                                       `menu_orders` INT NOT NULL,
                                                       `path` VARCHAR(255) NOT NULL,
                                                       `title` VARCHAR(45) NOT NULL,
                                                       `icon` VARCHAR(45) NULL,
                                                       `create_gmt` DATETIME NOT NULL,
                                                       `modified_gmt` DATETIME NULL,
                                                       PRIMARY KEY (`id`),
                                                       INDEX `fk_menu_menu_idx` (`parent_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_menu_menu1`
                                                           FOREIGN KEY (`parent_id`)
                                                               REFERENCES `hicorp_segment`.`menu` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`role_menu_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`role_menu_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`role_menu_relation` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `role_id` BIGINT UNSIGNED NOT NULL,
                                                                     `menu_id` BIGINT UNSIGNED NOT NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_role_menu_relation_role1_idx` (`role_id` ASC) VISIBLE,
                                                                     INDEX `fk_role_menu_relation_menu1_idx` (`menu_id` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_role_menu_relation_role1`
                                                                         FOREIGN KEY (`role_id`)
                                                                             REFERENCES `hicorp_segment`.`role` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_role_menu_relation_menu1`
                                                                         FOREIGN KEY (`menu_id`)
                                                                             REFERENCES `hicorp_segment`.`menu` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`staff` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`staff` (
                                                        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
                                                        `number` VARCHAR(45) NOT NULL,
                                                        `sex` TINYINT NOT NULL,
                                                        `identify` VARCHAR(18) NULL,
                                                        `create_user` VARCHAR(45) NOT NULL,
                                                        `create_gmt` DATETIME NOT NULL,
                                                        `modified_user` VARCHAR(45) NULL,
                                                        `modified_gmt` DATETIME NULL,
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '员工表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`basic_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`basic_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`basic_data` (
                                                             `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                             `category_number` VARCHAR(45) NOT NULL,
                                                             `category_name` VARCHAR(45) NOT NULL,
                                                             `type` VARCHAR(45) NULL,
                                                             `create_user` VARCHAR(45) NOT NULL,
                                                             `create_gmt` DATETIME NOT NULL,
                                                             `modified_user` VARCHAR(45) NULL,
                                                             `modified_gmt` DATETIME NULL,
                                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '基础数据表，存放部门、工种等信息。';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`material_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`material_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`material_data` (
                                                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                `number` VARCHAR(45) NOT NULL,
                                                                `name` VARCHAR(45) NOT NULL,
                                                                `type` ENUM('自制件', '原材料', '零配件') NOT NULL,
                                                                `spec` VARCHAR(45) NULL COMMENT '规格',
                                                                `safety_stock` VARCHAR(45) NULL COMMENT '安全库存',
                                                                `create_user` VARCHAR(45) NOT NULL,
                                                                `create_gmt` DATETIME NOT NULL,
                                                                `modified_user` VARCHAR(45) NULL,
                                                                `modified_gmt` DATETIME NULL,
                                                                PRIMARY KEY (`id`),
                                                                UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = '物料表\n包含自制件，原材料，零配件';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`bom_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`bom_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`bom_data` (
                                                           `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                           `number` VARCHAR(45) NOT NULL,
                                                           `material_number` VARCHAR(45) NOT NULL,
                                                           `material_name` VARCHAR(45) NOT NULL,
                                                           `version` VARCHAR(45) NOT NULL,
                                                           `is_enable` TINYINT NOT NULL DEFAULT 1,
                                                           `unit` VARCHAR(45) NOT NULL,
                                                           `compile_user` VARCHAR(45) NULL,
                                                           `reviewer_user` VARCHAR(45) NULL,
                                                           `create_user` VARCHAR(45) NOT NULL,
                                                           `create_gmt` DATETIME NOT NULL,
                                                           `modified_user` VARCHAR(45) NULL,
                                                           `modified_time` DATETIME NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = 'BOM主表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`material_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`material_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`material_relation` (
                                                                    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                    `bom_number` VARCHAR(45) NOT NULL COMMENT 'BOM主键',
                                                                    `parent_id` BIGINT UNSIGNED NULL COMMENT '父类id',
                                                                    `parent_material_number` VARCHAR(45) NULL COMMENT '主物料编码(父类物料的编码)',
                                                                    `material_number` VARCHAR(45) NOT NULL COMMENT '物料编码',
                                                                    `material_name` VARCHAR(45) NOT NULL COMMENT '物料名称',
                                                                    `quantity` INT NOT NULL COMMENT '数量',
                                                                    `unit` VARCHAR(8) NOT NULL COMMENT '计量单位',
                                                                    `create_user` VARCHAR(45) NOT NULL,
                                                                    `create_gmt` DATETIME NOT NULL,
                                                                    `modified_user` VARCHAR(45) NULL,
                                                                    `modified_gmt` DATETIME NULL,
                                                                    PRIMARY KEY (`id`),
                                                                    INDEX `fk_material_relation_material_relation_idx` (`parent_id` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_bom_data_idx` (`bom_number` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_material_data1_idx` (`parent_material_number` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_material_data2_idx` (`material_number` ASC) VISIBLE,
                                                                    CONSTRAINT `fk_material_relation_material_relation1`
                                                                        FOREIGN KEY (`parent_id`)
                                                                            REFERENCES `hicorp_segment`.`material_relation` (`id`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_bom_data1`
                                                                        FOREIGN KEY (`bom_number`)
                                                                            REFERENCES `hicorp_segment`.`bom_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_material_data1`
                                                                        FOREIGN KEY (`parent_material_number`)
                                                                            REFERENCES `hicorp_segment`.`material_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_material_data2`
                                                                        FOREIGN KEY (`material_number`)
                                                                            REFERENCES `hicorp_segment`.`material_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '物料关系(BOM子表)';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme` (
                                                                 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `number` VARCHAR(45) NOT NULL COMMENT '方案编码',
                                                                 `name` VARCHAR(45) NOT NULL,
                                                                 `create_user` VARCHAR(45) NOT NULL,
                                                                 `create_gmt` DATETIME NOT NULL,
                                                                 `modified_user` VARCHAR(45) NULL,
                                                                 `modified_gmt` DATETIME NULL,
                                                                 PRIMARY KEY (`id`),
                                                                 UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = '工艺方案主表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme_sub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme_sub` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme_sub` (
                                                                     `id` BIGINT UNSIGNED NOT NULL,
                                                                     `process_number` VARCHAR(45) NOT NULL,
                                                                     `scheme_name` VARCHAR(45) NOT NULL COMMENT '工艺方案名称',
                                                                     `process_name` VARCHAR(45) NOT NULL COMMENT '工序名称',
                                                                     `pre_process` VARCHAR(45) NULL,
                                                                     `post_process` VARCHAR(45) NULL,
                                                                     `quality_inspection_scheme` VARCHAR(45) NULL COMMENT '质检方案',
                                                                     `is_compile_process_plan` TINYINT NOT NULL COMMENT '是否编制工序计划',
                                                                     `is_print` TINYINT NOT NULL COMMENT '完工后是否打印标签',
                                                                     `plan_report` VARCHAR(45) NOT NULL COMMENT '是否计划和报工',
                                                                     `participation_role` VARCHAR(45) NULL,
                                                                     `work_description` VARCHAR(255) NULL,
                                                                     `man_hour_quota` VARCHAR(45) NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_process_scheme_sub_process_scheme1_idx` (`process_number` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_process_scheme_sub_process_scheme1`
                                                                         FOREIGN KEY (`process_number`)
                                                                             REFERENCES `hicorp_segment`.`process_scheme` (`number`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '工艺方案子表(工序表)';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme_bom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme_bom` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme_bom` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `bom_number` VARCHAR(45) NOT NULL COMMENT 'BOM主键',
                                                                     `material_number` VARCHAR(45) NOT NULL,
                                                                     `material_name` VARCHAR(45) NOT NULL,
                                                                     `process_scheme` VARCHAR(45) NOT NULL,
                                                                     `pre_process` VARCHAR(45) NULL,
                                                                     `post_process` VARCHAR(45) NULL,
                                                                     `quality_inspection_scheme` VARCHAR(45) NULL,
                                                                     `is_compile_process_plan` TINYINT NOT NULL COMMENT '是否编制工序计划',
                                                                     `is_print` TINYINT NOT NULL COMMENT '完工后是否打印标签',
                                                                     `plan_report` VARCHAR(45) NOT NULL COMMENT '是否计划和报工',
                                                                     `participation_role` VARCHAR(45) NULL,
                                                                     `work_description` VARCHAR(255) NULL,
                                                                     `man_hour_quota` VARCHAR(45) NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_process_scheme_bom_bom_data1_idx` (`bom_number` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_process_scheme_bom_bom_data1`
                                                                         FOREIGN KEY (`bom_number`)
                                                                             REFERENCES `hicorp_segment`.`bom_data` (`number`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '工艺BOM子表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
