-- MySQL Script generated by MySQL Workbench
-- Mon May 17 22:27:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema haier_erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `haier_erp` DEFAULT CHARACTER SET utf8;
USE `haier_erp`;


-- -----------------------------------------------------
-- Table `haier_erp`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`user_info`
(
    `id`           bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name`         varchar(45)         NOT NULL,
    `staff_number` varchar(45)         NOT NULL,
    `phone_number` varchar(16) DEFAULT NULL,
    `id_card`      varchar(18) DEFAULT NULL,
    `sex`          tinyint(4)  DEFAULT NULL,
    `gmt_create`   datetime            NOT NULL,
    `gmt_modified` datetime    DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`user`
(
    `id`           bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `user_info_id` bigint(20) unsigned NOT NULL,
    `user_name`    varchar(45)         NOT NULL,
    `password`     varchar(255)        NOT NULL,
    `gmt_create`   datetime            NOT NULL,
    `gmt_modified` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `user_name_UNIQUE` (`user_name`),
    KEY `fk_user_user_info1_idx` (`user_info_id`),
    CONSTRAINT `fk_user_user_info1` FOREIGN KEY (`user_info_id`) REFERENCES `haier_erp`.`user_info` (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`role`
(
    `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`         VARCHAR(45)     NOT NULL,
    `gmt_create`   DATETIME        NOT NULL,
    `gmt_modified` DATETIME        NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`user_role_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`user_role_relation`
(
    `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`      BIGINT UNSIGNED NOT NULL,
    `role_id`      BIGINT UNSIGNED NOT NULL,
    `gmt_create`   DATETIME        NOT NULL,
    `gmt_modified` DATETIME        NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_user_role_relation_role1_idx` (`role_id` ASC) VISIBLE,
    INDEX `fk_user_role_relation_user_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_user_role_relation_user` FOREIGN KEY (`user_id`) REFERENCES `haier_erp`.`user` (`id`),
    CONSTRAINT `fk_user_role_relation_role1` FOREIGN KEY (`role_id`) REFERENCES `haier_erp`.`role` (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`menu`
(
    `id`            bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `parent_id`     bigint(20) unsigned DEFAULT NULL,
    `name`          varchar(45)         NOT NULL,
    `link`          varchar(255)        NOT NULL,
    `create_user`   varchar(45)         NOT NULL,
    `gmt_create`    datetime            NOT NULL,
    `modified_user` varchar(45)         DEFAULT NULL,
    `gmt_modified`  datetime            DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_menu_menu1_idx` (`parent_id`),
    KEY `fk_menu_user1_idx` (`create_user`),
    KEY `fk_menu_user2_idx` (`modified_user`),
    CONSTRAINT `fk_menu_menu1` FOREIGN KEY (`parent_id`) REFERENCES `menu` (`id`),
    CONSTRAINT `fk_menu_user1` FOREIGN KEY (`create_user`) REFERENCES `user` (`user_name`),
    CONSTRAINT `fk_menu_user2` FOREIGN KEY (`modified_user`) REFERENCES `user` (`user_name`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`role_menu_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`role_menu_relation`
(
    `id`            bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `role_id`       bigint(20) unsigned NOT NULL,
    `menu_id`       bigint(20) unsigned NOT NULL,
    `create_user`   varchar(45)         NOT NULL,
    `gmt_create`    datetime            NOT NULL,
    `modified_user` varchar(45) DEFAULT NULL,
    `gmt_modified`  datetime    DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_role_menu_relation_role1_idx` (`role_id`),
    KEY `fk_role_menu_relation_menu1_idx` (`menu_id`),
    KEY `fk_role_menu_relation_user1_idx` (`create_user`),
    KEY `fk_role_menu_relation_user2_idx` (`modified_user`),
    CONSTRAINT `fk_role_menu_relation_menu1` FOREIGN KEY (`menu_id`) REFERENCES `menu` (`id`),
    CONSTRAINT `fk_role_menu_relation_role1` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`),
    CONSTRAINT `fk_role_menu_relation_user1` FOREIGN KEY (`create_user`) REFERENCES `user` (`user_name`),
    CONSTRAINT `fk_role_menu_relation_user2` FOREIGN KEY (`modified_user`) REFERENCES `user` (`user_name`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`permission`
(
    `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`         VARCHAR(45)     NOT NULL,
    `url`          VARCHAR(255)    NOT NULL,
    `description`  VARCHAR(255)    NULL,
    `gmt_create`   DATETIME        NOT NULL,
    `gmt_modified` DATETIME        NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `haier_erp`.`login_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`login_record`
(
    `id`             bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `user_name`      varchar(45)         NOT NULL,
    `is_logout`      tinyint(4)          NOT NULL,
    `remote_address` varchar(20)         NOT NULL,
    `gmt_create`     datetime            NOT NULL,
    `gmt_modified`   datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_login_record_user1_idx` (`user_name`),
    CONSTRAINT `fk_login_record_user1` FOREIGN KEY (`user_name`) REFERENCES `haier_erp`.`user` (`user_name`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haier_erp`.`operation_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haier_erp`.`operation_record`
(
    `id`             bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `user_name`      varchar(45)         NOT NULL,
    `ip`             varchar(20)         NOT NULL,
    `operation`      varchar(45)         NOT NULL,
    `request_detail` varchar(255)        NOT NULL,
    `use_method`     varchar(255)        NOT NULL,
    `params`         text                NOT NULL,
    `gmt_create`     datetime            NOT NULL,
    `gmt_modified`   datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_operation_record_user1_idx` (`user_name`),
    CONSTRAINT `fk_operation_record_user1` FOREIGN KEY (`user_name`) REFERENCES `user` (`user_name`)
) ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
