-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 20:29:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hicorp_segment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hicorp_segment` ;

-- -----------------------------------------------------
-- Schema hicorp_segment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hicorp_segment` DEFAULT CHARACTER SET utf8 ;
USE `hicorp_segment` ;

-- -----------------------------------------------------
-- Table `hicorp_segment`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`user` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`user` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `user_name` VARCHAR(16) NOT NULL COMMENT 'User login account.',
                                                       `password` VARCHAR(255) NOT NULL COMMENT 'User login password',
                                                       `create_gmt` DATETIME NOT NULL COMMENT 'Record create time  (Use Greenwich Mean Time).',
                                                       `modified_user` VARCHAR(45) NULL,
                                                       `modified_gmt` DATETIME NULL COMMENT 'Record modified time  (Use Greenwich Mean Time).',
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = 'This table just used to authenticate user login, only has account info, don`t has other user info.';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`role` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`role` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(16) NOT NULL,
                                                       `introduction` VARCHAR(255) NOT NULL,
                                                       `create_user` VARCHAR(45) NOT NULL,
                                                       `create_gmt` DATETIME NOT NULL,
                                                       `modified_user` VARCHAR(45) NULL,
                                                       `modified_gmt` DATETIME NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = 'This table stores role information.';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`user_role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`user_role_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`user_role_relation` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `user_id` BIGINT UNSIGNED NOT NULL,
                                                                     `role_id` BIGINT UNSIGNED NOT NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_user_role_relation_user_idx` (`user_id` ASC) VISIBLE,
                                                                     INDEX `fk_user_role_relation_role_idx` (`role_id` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_user_role_relation_user1`
                                                                         FOREIGN KEY (`user_id`)
                                                                             REFERENCES `hicorp_segment`.`user` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_user_role_relation_role1`
                                                                         FOREIGN KEY (`role_id`)
                                                                             REFERENCES `hicorp_segment`.`role` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`menu` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`menu` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `parent_id` BIGINT UNSIGNED NULL,
                                                       `menu_orders` INT NOT NULL,
                                                       `path` VARCHAR(255) NOT NULL,
                                                       `title` VARCHAR(45) NOT NULL,
                                                       `icon` VARCHAR(45) NULL,
                                                       `create_gmt` DATETIME NOT NULL,
                                                       `modified_gmt` DATETIME NULL,
                                                       PRIMARY KEY (`id`),
                                                       INDEX `fk_menu_menu_idx` (`parent_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_menu_menu1`
                                                           FOREIGN KEY (`parent_id`)
                                                               REFERENCES `hicorp_segment`.`menu` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`role_menu_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`role_menu_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`role_menu_relation` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `role_id` BIGINT UNSIGNED NOT NULL,
                                                                     `menu_id` BIGINT UNSIGNED NOT NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_role_menu_relation_role1_idx` (`role_id` ASC) VISIBLE,
                                                                     INDEX `fk_role_menu_relation_menu1_idx` (`menu_id` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_role_menu_relation_role1`
                                                                         FOREIGN KEY (`role_id`)
                                                                             REFERENCES `hicorp_segment`.`role` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_role_menu_relation_menu1`
                                                                         FOREIGN KEY (`menu_id`)
                                                                             REFERENCES `hicorp_segment`.`menu` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`staff` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`staff` (
                                                        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
                                                        `number` VARCHAR(45) NOT NULL,
                                                        `sex` TINYINT NOT NULL,
                                                        `identify` VARCHAR(18) NULL,
                                                        `is_user` TINYINT NOT NULL DEFAULT 0,
                                                        `user_account` VARCHAR(45) NULL,
                                                        `create_user` VARCHAR(45) NOT NULL,
                                                        `create_gmt` DATETIME NOT NULL,
                                                        `modified_user` VARCHAR(45) NULL,
                                                        `modified_gmt` DATETIME NULL,
                                                        PRIMARY KEY (`id`),
                                                        INDEX `fk_staff_user1_idx` (`user_account` ASC) VISIBLE,
                                                        CONSTRAINT `fk_staff_user1`
                                                            FOREIGN KEY (`user_account`)
                                                                REFERENCES `hicorp_segment`.`user` (`user_name`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '员工表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`basic_category_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`basic_category_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`basic_category_data` (
                                                                      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                      `number` VARCHAR(45) NOT NULL,
                                                                      `name` VARCHAR(45) NOT NULL,
                                                                      `type` VARCHAR(45) NULL,
                                                                      `create_user` VARCHAR(45) NOT NULL,
                                                                      `create_gmt` DATETIME NOT NULL,
                                                                      `modified_user` VARCHAR(45) NULL,
                                                                      `modified_gmt` DATETIME NULL,
                                                                      PRIMARY KEY (`id`),
                                                                      UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = '存放基础数据中的那些类别, 如工位类别、模具类别、工具类别等, 以及普通的无上下级关系的基础数据.';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`material_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`material_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`material_data` (
                                                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                `number` VARCHAR(45) NOT NULL,
                                                                `name` VARCHAR(45) NOT NULL,
                                                                `type` ENUM('自制件', '原材料', '零配件') NOT NULL,
                                                                `spec` VARCHAR(45) NULL COMMENT '规格',
                                                                `safety_stock` VARCHAR(45) NULL COMMENT '安全库存',
                                                                `create_user` VARCHAR(45) NOT NULL,
                                                                `create_gmt` DATETIME NOT NULL,
                                                                `modified_user` VARCHAR(45) NULL,
                                                                `modified_gmt` DATETIME NULL,
                                                                PRIMARY KEY (`id`),
                                                                UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = '物料表\n包含自制件，原材料，零配件';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`bom_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`bom_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`bom_data` (
                                                           `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                           `number` VARCHAR(45) NOT NULL,
                                                           `material_number` VARCHAR(45) NOT NULL,
                                                           `material_name` VARCHAR(45) NOT NULL,
                                                           `version` VARCHAR(45) NOT NULL,
                                                           `is_enable` TINYINT NOT NULL DEFAULT 1,
                                                           `unit` VARCHAR(45) NOT NULL,
                                                           `compile_user` VARCHAR(45) NULL,
                                                           `reviewer_user` VARCHAR(45) NULL,
                                                           `create_user` VARCHAR(45) NOT NULL,
                                                           `create_gmt` DATETIME NOT NULL,
                                                           `modified_user` VARCHAR(45) NULL,
                                                           `modified_time` DATETIME NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = 'BOM主表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`material_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`material_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`material_relation` (
                                                                    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                    `bom_number` VARCHAR(45) NOT NULL COMMENT 'BOM主键',
                                                                    `parent_id` BIGINT UNSIGNED NULL COMMENT '父类id',
                                                                    `parent_material_number` VARCHAR(45) NULL COMMENT '主物料编码(父类物料的编码)',
                                                                    `material_number` VARCHAR(45) NOT NULL COMMENT '物料编码',
                                                                    `material_name` VARCHAR(45) NOT NULL COMMENT '物料名称',
                                                                    `quantity` INT NOT NULL COMMENT '数量',
                                                                    `unit` VARCHAR(8) NOT NULL COMMENT '计量单位',
                                                                    `create_user` VARCHAR(45) NOT NULL,
                                                                    `create_gmt` DATETIME NOT NULL,
                                                                    `modified_user` VARCHAR(45) NULL,
                                                                    `modified_gmt` DATETIME NULL,
                                                                    PRIMARY KEY (`id`),
                                                                    INDEX `fk_material_relation_material_relation_idx` (`parent_id` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_bom_data_idx` (`bom_number` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_material_data1_idx` (`parent_material_number` ASC) VISIBLE,
                                                                    INDEX `fk_material_relation_material_data2_idx` (`material_number` ASC) VISIBLE,
                                                                    CONSTRAINT `fk_material_relation_material_relation1`
                                                                        FOREIGN KEY (`parent_id`)
                                                                            REFERENCES `hicorp_segment`.`material_relation` (`id`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_bom_data1`
                                                                        FOREIGN KEY (`bom_number`)
                                                                            REFERENCES `hicorp_segment`.`bom_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_material_data1`
                                                                        FOREIGN KEY (`parent_material_number`)
                                                                            REFERENCES `hicorp_segment`.`material_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_material_relation_material_data2`
                                                                        FOREIGN KEY (`material_number`)
                                                                            REFERENCES `hicorp_segment`.`material_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '物料关系(BOM子表)';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme` (
                                                                 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `number` VARCHAR(45) NOT NULL COMMENT '方案编码',
                                                                 `name` VARCHAR(45) NOT NULL,
                                                                 `create_user` VARCHAR(45) NOT NULL,
                                                                 `create_gmt` DATETIME NOT NULL,
                                                                 `modified_user` VARCHAR(45) NULL,
                                                                 `modified_gmt` DATETIME NULL,
                                                                 PRIMARY KEY (`id`),
                                                                 UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
    ENGINE = InnoDB
    COMMENT = '工艺方案主表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme_sub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme_sub` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme_sub` (
                                                                     `id` BIGINT UNSIGNED NOT NULL,
                                                                     `process_number` VARCHAR(45) NOT NULL,
                                                                     `scheme_name` VARCHAR(45) NOT NULL COMMENT '工艺方案名称',
                                                                     `process_name` VARCHAR(45) NOT NULL COMMENT '工序名称',
                                                                     `pre_process` VARCHAR(45) NULL,
                                                                     `post_process` VARCHAR(45) NULL,
                                                                     `quality_inspection_scheme` VARCHAR(45) NULL COMMENT '质检方案',
                                                                     `is_compile_process_plan` TINYINT NOT NULL COMMENT '是否编制工序计划',
                                                                     `is_print` TINYINT NOT NULL COMMENT '完工后是否打印标签',
                                                                     `plan_report` VARCHAR(45) NOT NULL COMMENT '是否计划和报工',
                                                                     `participation_role` VARCHAR(45) NULL,
                                                                     `work_description` VARCHAR(255) NULL,
                                                                     `man_hour_quota` VARCHAR(45) NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_process_scheme_sub_process_scheme1_idx` (`process_number` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_process_scheme_sub_process_scheme1`
                                                                         FOREIGN KEY (`process_number`)
                                                                             REFERENCES `hicorp_segment`.`process_scheme` (`number`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '工艺方案子表(工序表)';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`process_scheme_bom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`process_scheme_bom` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`process_scheme_bom` (
                                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                     `bom_number` VARCHAR(45) NOT NULL COMMENT 'BOM主键',
                                                                     `material_number` VARCHAR(45) NOT NULL,
                                                                     `material_name` VARCHAR(45) NOT NULL,
                                                                     `process_scheme` VARCHAR(45) NOT NULL,
                                                                     `pre_process` VARCHAR(45) NULL,
                                                                     `post_process` VARCHAR(45) NULL,
                                                                     `quality_inspection_scheme` VARCHAR(45) NULL,
                                                                     `is_compile_process_plan` TINYINT NOT NULL DEFAULT 0 COMMENT '是否编制工序计划',
                                                                     `is_print` TINYINT NOT NULL DEFAULT 0 COMMENT '完工后是否打印标签',
                                                                     `plan_report` VARCHAR(45) NOT NULL COMMENT '是否计划和报工',
                                                                     `participation_role` VARCHAR(45) NULL,
                                                                     `work_description` VARCHAR(255) NULL,
                                                                     `man_hour_quota` VARCHAR(45) NULL,
                                                                     `create_user` VARCHAR(45) NOT NULL,
                                                                     `create_gmt` DATETIME NOT NULL,
                                                                     `modified_user` VARCHAR(45) NULL,
                                                                     `modified_gmt` DATETIME NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     INDEX `fk_process_scheme_bom_bom_data1_idx` (`bom_number` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_process_scheme_bom_bom_data1`
                                                                         FOREIGN KEY (`bom_number`)
                                                                             REFERENCES `hicorp_segment`.`bom_data` (`number`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '工艺BOM子表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`login_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`login_record` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`login_record` (
                                                               `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                               `user_name` VARCHAR(45) NOT NULL,
                                                               `is_logout` TINYINT NOT NULL DEFAULT 0,
                                                               `remote_address` VARCHAR(45) NULL,
                                                               `create_gmt` DATETIME NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `fk_login_record_user1_idx` (`user_name` ASC) VISIBLE,
                                                               CONSTRAINT `fk_login_record_user1`
                                                                   FOREIGN KEY (`user_name`)
                                                                       REFERENCES `hicorp_segment`.`user` (`user_name`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`permission` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`permission` (
                                                             `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                             `tag` VARCHAR(45) NOT NULL,
                                                             `method` CHAR(8) NOT NULL,
                                                             `api_path` VARCHAR(255) NOT NULL,
                                                             `operation_id` VARCHAR(255) NULL DEFAULT NULL,
                                                             `summary` VARCHAR(255) NULL DEFAULT NULL,
                                                             `description` VARCHAR(255) NULL DEFAULT NULL,
                                                             `create_gmt` DATETIME NOT NULL,
                                                             `modified_gmt` DATETIME NULL DEFAULT NULL,
                                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`role_permission_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`role_permission_relation` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`role_permission_relation` (
                                                                           `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                           `role_id` BIGINT UNSIGNED NOT NULL,
                                                                           `permission_id` BIGINT UNSIGNED NOT NULL,
                                                                           `create_user` VARCHAR(45) NOT NULL,
                                                                           `create_gmt` DATETIME NOT NULL,
                                                                           PRIMARY KEY (`id`),
                                                                           INDEX `fk_role_permission_relation_role1_idx` (`role_id` ASC) VISIBLE,
                                                                           INDEX `fk_role_permission_relation_permission1_idx` (`permission_id` ASC) VISIBLE,
                                                                           CONSTRAINT `fk_role_permission_relation_role1`
                                                                               FOREIGN KEY (`role_id`)
                                                                                   REFERENCES `hicorp_segment`.`role` (`id`)
                                                                                   ON DELETE NO ACTION
                                                                                   ON UPDATE NO ACTION,
                                                                           CONSTRAINT `fk_role_permission_relation_permission1`
                                                                               FOREIGN KEY (`permission_id`)
                                                                                   REFERENCES `hicorp_segment`.`permission` (`id`)
                                                                                   ON DELETE NO ACTION
                                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`operation_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`operation_record` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`operation_record` (
                                                                   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                   `user_name` VARCHAR(45) NOT NULL COMMENT '执行操作的用户',
                                                                   `ip` VARCHAR(20) NOT NULL COMMENT '用户的ip地址',
                                                                   `operation` VARCHAR(45) NOT NULL COMMENT '具体执行的操作内容',
                                                                   `request_detail` VARCHAR(255) NOT NULL COMMENT '详细请求内容(请求的接口url)',
                                                                   `use_method` VARCHAR(255) NOT NULL COMMENT '发送的请求类别(post/get/delete/put)',
                                                                   `params` TEXT NOT NULL COMMENT '请求的参数',
                                                                   `create_gmt` DATETIME NOT NULL COMMENT '操作的时间',
                                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`approve_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`approve_process` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`approve_process` (
                                                                  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                  `number` VARCHAR(45) NOT NULL,
                                                                  `table_name` VARCHAR(45) NOT NULL COMMENT '审批所对应的表的名字。',
                                                                  `content` VARCHAR(255) NULL COMMENT '审批内容',
                                                                  `level` INT NOT NULL COMMENT '审批级别',
                                                                  `approver` VARCHAR(45) NOT NULL COMMENT '审批人',
                                                                  `pre_approver` VARCHAR(45) NULL COMMENT '前一级的审批人',
                                                                  `post_approver` VARCHAR(45) NULL COMMENT '后一级的审批人',
                                                                  `create_user` VARCHAR(45) NOT NULL,
                                                                  `create_gmt` DATETIME NOT NULL,
                                                                  `modified_user` VARCHAR(45) NULL,
                                                                  `modified_gmt` DATETIME NULL,
                                                                  PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '审批流表，设置哪个流程需要审批，具体有几级审批，每级审批人(或负责审批的角色)是谁。';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`approve_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`approve_status` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`approve_status` (
                                                                 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `approver_table_name` VARCHAR(45) NOT NULL COMMENT '审批的表的名称',
                                                                 `detail_column_id` BIGINT NOT NULL COMMENT '具体审核的是哪一条单据(数据)',
                                                                 `current_approver` VARCHAR(45) NOT NULL,
                                                                 `is_approved` TINYINT NOT NULL DEFAULT 0,
                                                                 `status` VARCHAR(45) NOT NULL COMMENT '审批状态, 例如: 已通过、已退回、已超时等。',
                                                                 `create_user` VARCHAR(45) NOT NULL,
                                                                 `create_gmt` DATETIME NOT NULL,
                                                                 `modified_user` VARCHAR(45) NULL,
                                                                 `modified_gmt` DATETIME NULL,
                                                                 PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '审批状态表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`approve_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`approve_record` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`approve_record` (
                                                                 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `approver_table_name` VARCHAR(45) NOT NULL COMMENT '审批的表的名称',
                                                                 `detail_column_id` BIGINT NOT NULL COMMENT '具体审核的是哪一条单据(数据)',
                                                                 `current_approver` VARCHAR(45) NOT NULL,
                                                                 `pre_approver` VARCHAR(45) NULL,
                                                                 `post_approver` VARCHAR(45) NULL,
                                                                 `is_end` TINYINT NOT NULL,
                                                                 `is_approved` TINYINT NOT NULL DEFAULT 0,
                                                                 `approval_comments` VARCHAR(45) NOT NULL COMMENT '审批意见',
                                                                 `status` VARCHAR(45) NOT NULL COMMENT '审批状态, 例如: 已通过、已退回、已超时等。',
                                                                 `create_user` VARCHAR(45) NOT NULL,
                                                                 `create_gmt` DATETIME NOT NULL,
                                                                 `modified_user` VARCHAR(45) NULL,
                                                                 `modified_gmt` DATETIME NULL,
                                                                 PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '审批记录表';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`device_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`device_category` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`device_category` (
                                                                  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                  `purpose` ENUM('前端设备', '机房设备', '路由相关') NOT NULL,
                                                                  `name` VARCHAR(45) NOT NULL COMMENT '类别名称',
                                                                  `number` VARCHAR(45) NOT NULL COMMENT '编号',
                                                                  `brand` VARCHAR(45) NOT NULL,
                                                                  `specification_model` VARCHAR(45) NOT NULL,
                                                                  `unit` VARCHAR(45) NOT NULL,
                                                                  `remarks` VARCHAR(45) NOT NULL,
                                                                  `create_user` VARCHAR(45) NOT NULL,
                                                                  `create_gmt` DATETIME NOT NULL,
                                                                  `modified_user` VARCHAR(45) NULL DEFAULT NULL,
                                                                  `modified_gmt` DATETIME NULL DEFAULT NULL,
                                                                  PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`device` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`device` (
                                                         `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         `number` VARCHAR(45) NOT NULL COMMENT '设备编号',
                                                         `name` VARCHAR(45) NOT NULL COMMENT '设备名',
                                                         `address` VARCHAR(255) NOT NULL COMMENT '存放点位',
                                                         `status` VARCHAR(45) NOT NULL COMMENT '状态(维修、使用中、年检中、报废等)',
                                                         `use_begin` DATE NOT NULL COMMENT '何时开始使用？',
                                                         `create_user` VARCHAR(45) NOT NULL,
                                                         `create_gmt` DATETIME NOT NULL,
                                                         `modified_user` VARCHAR(45) NULL DEFAULT NULL,
                                                         `modified_gmt` DATETIME NULL DEFAULT NULL,
                                                         PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hicorp_segment`.`basic_detail_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`basic_detail_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`basic_detail_data` (
                                                                    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                    `number` VARCHAR(45) NOT NULL,
                                                                    `name` VARCHAR(45) NOT NULL,
                                                                    `category_number` VARCHAR(45) NOT NULL,
                                                                    `category_name` VARCHAR(45) NOT NULL,
                                                                    `type` VARCHAR(45) NULL,
                                                                    `create_user` VARCHAR(45) NOT NULL,
                                                                    `create_gmt` DATETIME NOT NULL,
                                                                    `modified_user` VARCHAR(45) NULL,
                                                                    `modified_gmt` DATETIME NULL,
                                                                    PRIMARY KEY (`id`),
                                                                    INDEX `fk_basic_detail_data_basic_category_data1_idx` (`category_number` ASC) VISIBLE,
                                                                    CONSTRAINT `fk_basic_detail_data_basic_category_data1`
                                                                        FOREIGN KEY (`category_number`)
                                                                            REFERENCES `hicorp_segment`.`basic_category_data` (`number`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '基础数据中那些类别的子项，如：工位、仓库、模具、工具等';


-- -----------------------------------------------------
-- Table `hicorp_segment`.`basic_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hicorp_segment`.`basic_data` ;

CREATE TABLE IF NOT EXISTS `hicorp_segment`.`basic_data` (
                                                             `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB
    COMMENT = '有上下级关系的基础数据, 暂未使用';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
